name: xnap-projecte
channels:
- pytorch
- defaults
dependencies:
- python=3.8
- pytorch
- numpy
- tqdm
- pandas
- tensorboard
- protobuf<=3.20
- pip
- pip:
  - torchvision
  - onnx
  - wandb
  - onnxruntime
  - ipykernel
  - spacy
  - joblib
  - pandas
