wandb_version: 1

root_dir:
  desc: null
  value: ../data/Images
captions_file:
  desc: null
  value: ../data/captions.txt
transforms:
  desc: null
  value: "Compose(\n    Resize(size=226, interpolation=bilinear, max_size=None, antialias=warn)\n\
    \    RandomCrop(size=(224, 224), padding=None)\n    ToTensor()\n    Normalize(mean=(0.485,\
    \ 0.456, 0.406), std=(0.229, 0.224, 0.225))\n)"
embed_size:
  desc: null
  value: 300
attention_dim:
  desc: null
  value: 256
encoder_dim:
  desc: null
  value: 2048
decoder_dim:
  desc: null
  value: 512
epochs:
  desc: null
  value: 25
learning_rate:
  desc: null
  value: 0.0003
batch_size:
  desc: null
  value: 256
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685087157.205918
    t:
      1:
      - 1
      - 5
      - 33
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 33
      - 41
      - 53
      - 55
      3:
      - 2
      - 16
      - 19
      - 23
      4: 3.8.16
      5: 0.15.3
      8:
      - 3
      - 5
vocab_size:
  desc: null
  value: 2994
